### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by tamimuiuc**
Mohammad Tamim
tamim2@illinois.edu

### Pull Request - Addition of Sepsis-3 Mortality Prediction Models and Datasets

This pull request includes several components that extend PyHealth's capabilities for analyzing mortality in sepsis patients using the MIMIC-III dataset.

#### Changes include:
- `datasets/mimic3_sepsis3.py`: A dataset script for preprocessing sepsis-related data.
- `tasks/mortality_prediction_sepsis3.py`: A task definition for mortality prediction.
- `models/xgboost.py`: An XGBoost model tailored for predicting mortality.
- `examples/mortality_mimic3_sepsis3.py`: An example script demonstrating the workflow from data loading to prediction.

I've tested these additions with data from the MIMIC-III public dataset, focusing on ensuring compatibility and performance within the existing PyHealth framework.

I welcome any feedback on code style, performance improvements, or integration aspects. Thank you for considering this contribution!

### CODE REVIEW

**Comment by tamimuiuc** [comment]
Hello,

I've completed the requested changes and there are no conflicts with the base branch. Could you please confirm the next steps for merging this pull request? Do I need to take any further action?

Additionally, I would like to confirm that this contribution meets the requirements for the 10 bonus points as outlined in the course instructions. If there is any additional information or action needed from my side, please let me know.

Thank you!

**Comment by ycq091044** [comment]
Hi @tamimuiuc , thanks for your PR. I have started to test your PR locally.
1. It seems that the current dataset does not support the internal ``stat()`` function.
image

**Comment by ycq091044** [comment]
Hello, I have carefully reviewed your PR.
1. the CSV sepsis dataframe is somewhat useful as an addition to the package.
2. the task function is not helpful.
3. the example does not run (xgb.XGBClassifier needs X and y as input, but you use one dataframe).

We will give partial bonus points based on this.

**Comment by tamimuiuc** [comment]
@ycq091044 
Thank you for your feedback. Actually, the XGBClassifier uses:
- feature_keys=['urineoutput', 'lactate_min', 'bun_mean', 'sysbp_min', 'metastatic_cancer', 'inr_max', 'age', 'sodium_max', 'aniongap_max', 'creatinine_min', 'spo2_mean'] as x.
- label_key='thirtyday_expire_flag' as y.
The code should run successfully on your end as it does on mine.

**Comment by ycq091044** [comment]
Y, I can quickly make it run. There are just some minor bugs, such as XGBClassifier is not imported anywhere.

**Comment by tamimuiuc** [comment]
Hi, in 'xgboost.py', I did 'import xgboost as xgb' and created 'XGBoostModel' class. Also, in 'mortality_mimic3_sepsis3.py', I did both 'import xgboost as xgb' and called 'XGBoostModel'. You should be able to run the classifier successfully.

**Comment by ycq091044** [comment]
WHERE DID YOU IMPORT XGBoostModel in mortality_mimic3_sepsis3.py?

**Comment by tamimuiuc** [comment]
I see, you are right. I compiled all the code in Google Colab and ran it there. I did not import XGBoostModel.Thank you!

**Pull request merged**
