### PR TITLE
Removed obsolete column parsing in MIMIC-IV

### PR DESCRIPTION
**Pull request by WaicongTam**
The "race" column is now obsolete in the latest version of the MIMIC-IV release. Keeping the parsing of this column will lead to error for the creation of MIMIC-IV dataset.

### CODE REVIEW

**Comment by zzachw** [comment]
Hi @WaicongTam! Thanks for the PR! Could you specify the MIMIC-IV version you are using? It seems the 2.2 version still has the "race" column in the "admissions.csv" table.

**Comment by WaichungTam** [comment]
Hi @zzachw , I double-checked the table (I am also using 2.2). The column has been renamed to "ethnicity" (same as MIMIC-III but in lowercase). I will commit and test the new modification and raise the PR again. Apologies for the recklessness and thanks for the great work.

**Comment by WaichungTam** [comment]
Hi @zzachw the latest commit is with the new edits. Thanks!

**Comment by ycq091044** [comment]
Hello @zzachw, could you follow up this PR?

**Comment by ycq091044** [comment]
Hi @WaicongTam, according to the documents, the column name is still "race". https://mimic.mit.edu/docs/iv/modules/hosp/admissions/. Could you double-check again? Otherwise, you may close the PR. Thanks very much for your contributions.

**Comment by WaichungTam** [comment]
Hi Chaoqi,
The document is inconsistent. If you scroll down or look at the columns of
the CSV, it’s  ethnicity.

Again, thanks for the great work!

**Comment by ycq091044** [comment]
Hi @WaicongTam , thanks. To verify, I just downloaded the MIMIC-IV and double-checked the column. The name is "race", please take a look at the screenshot.

image

**Pull request closed without merging**
