### PR TITLE
Fix incorrect usage examples in Readme

### PR DESCRIPTION
**Pull request by Poehavshi**
train_dataset, val_dataset, test_dataset are undefined variables in STEP 2: <pyhealth.tasks> of ML Pipeline Example

### CODE REVIEW

**Review by ycq091044 — APPROVED** [review]
LGTM, thanks @Poehavshi very much for your contribution. Will merge it into the master branch soon.

**Review by pat-jj — APPROVED** [review]
Looks good, thank you so much for the contribution!

**Comment by ycq091044** [comment]
@Poehavshi You can go ahead and "rebase and merge" into our master branch.

**Comment by Poehavshi** [comment]
I don't have permissions for this
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can  merge pull requests.

**Pull request merged**
